- package.json
- yarn.lock
This should fix the issue encountered in #3. It looks like there's a bug in `yarn` where it brings in peer dependencies when it shouldn't, but I don't think that will affect this change!
> Fixed incorrect dependency definitions

- src/files/index.js
- src/files/list-thumbnail.js
- src/files/table.js
- src/folders/index.js
- src/folders/list-thumbnail.js
- src/folders/table.js
- src/headers/table.js
This isn't hugely pretty, and components should be composed rather than extended, BUT, for convenience, this PR exposes the raw, undecorated versions of all of the renderers.
Those who choose to extend these raw renderers should then decorate their extended component with the dnd stuff (just import and copy the same decoration that's done in the respective file) if they want dnd to work.
Fixes #16
> Expose renderers for extension

- src/folders/table.js
Added RawRableFolder export statement to allow for custom component creation.  
Looks like it was forgotten in this commit: https://github.com/uptick/react-keyed-file-browser/pull/17/commits/3c7bbf1f6ee654a92f41043bca5ed69d3d711452#diff-6eadf05f2571b5f56472ad582b259eb5
> Add export for RawTableFolder

- README.md
- demo-site/demos.sass
- demo-site/grouped-thumbnails.js
- demo-site/nested-editable.js
- src/base-file.js
- src/browser.js
- src/files/list-thumbnail.js
- src/files/table.js
- src/folders/list-thumbnail.js
- src/folders/table.js
- src/icons/FontAwesome.js
- src/icons/index.js
- src/index.js
Fixes #26
Remove dependency on font awesome 4 by allowing users to specify their own icons using the icons prop.
i.e.
```
<FileBrowser icons={{FavouritesIcon: <MyFavourites />}} />
```
Defaults added for FA4 FA5, use:
```
import {FontAwesome} from 'react-keyed-file-browser'
<FileBrowser icons={FontAwesome(5)} />
```
This will check if the required version of font awesome is loaded in the DOM and warn if not.
Either way it'll apply the icons you picked (so as not to cause problems for false negatives)
> Allow FontAwesome icons to be overridden

- src/browser.js
Message displayed when there were no files to display was static. The old message is stored as a default prop, new messages can be controlled through the `noFileMessage` prop.
> Change message when no files are visible to dynamic - use props.

- src/base-file.js
- src/base-folder.js
- src/browser.js
- src/files/list-thumbnail.js
- src/files/table.js
- src/filters/default.js
- src/folders/list-thumbnail.js
- src/folders/table.js
The use of [legacy string refs](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) prevented me from making any edits, as noted in #34. This should bring the ref usage up to the modern era without making any functional changes.
> String refs (legacy) -> callback refs

- src/base-file.js
- src/base-folder.js
- src/browser.js
Adds callbacks for:
-    onSelect          `// Always called when a file or folder is selected`
-    onSelectFile      `//    Called after onSelect, only on file selection`
-    onSelectFolder    `//    Called after onSelect, only on folder selection`
-    onPreviewOpen     `// File opened`
-    onPreviewClose    `// File closed`
-    onFolderOpen      `// Folder opened`
-    onFolderClose     `// Folder closed`
Allow customizing interactivity of the file browser without requiring overriding the renderers. Specifically for me, this enabled me to trigger loading each subfolder's files dynamically from S3 whenever a folder is opened. I believe the addition of callback hooks will also greatly ease e.g. #35.
> Adding interaction callbacks

- src/base-file.js
- src/base-folder.js
The drag event fires the onRenameFile / onRenameFolder functions, but this way it was not possible to identify whether the user is performing a name change or a drag action. With this change it will be possible to collect these two actions without impacting the existing functionalities.
> Improvement on drag events

- src/browser.js
- src/icons/FontAwesome.js
This allows the addition of an `onDownloadFile` prop
> Download action and icons for downloading files

- demo-site/nested-editable.js
- src/base-file.js
- src/base-folder.js
JIRA PBI https://uptickhq.atlassian.net/browse/UP-1895 
**STATUS: DO NOT MERGE**
Backslashes in folder/file names resulting in:
- unable to rename
- unable to re-sort
- unable to delete
Fixes:
[x] On creation of a new folder, backslashes are no longer allowed
[x] Old folders with a backslash can now be renamed
[x] Subfolders are not allowed forward/back slashes
[ ]  On creation of a new file, backslashes are no longer allowed
[ ] Old files with a backslash can now be renamed
[ ] Folders/Files with backslashes can now be re-sorted
> UP-1895 Documents - no more backslash havoc

- src/browser.js
The other callbacks are wrapped, so not sure if you just missed this one. Without wrapping it I get an error if my callback returns a promise.
> wrap onCreateFolder callback

- src/actions/default.js
- src/actions/index.js
- src/browser.js
This adds customization support to the action buttons
this can help with #19 until proper localization support is implemented
> Add a renderer for actions

- src/browser.js
the other renderers have it and can be very useful when using a
user-defined ActionRenderer
Personally I found this useful because I'm using a custom ActionRenderer to translate the action buttons to my language and style the buttons, but now I wan to add a new button to the action bar and this allows me to pass a new prop to <FileBrowser/> and have it available on ActionRenderer via browserProps
> Make browserProps available on ActionRenderer

- src/browser.js
- src/confirmations/default.js
- src/confirmations/index.js
- src/files/list-thumbnail.js
- src/files/table.js
- src/folders/list-thumbnail.js
- src/folders/table.js
This PR will address issue #82 in a manner outlined by contributor:  @jlo-1 .
This update exposes a new `confirmDeletionRenderer` prop to FileBrowser which takes in 4 props:  handleDeleteSubmit, handleFileClick, url, and children.
The old behavior is maintained and has been modularized out into `src/confirmations/default.js`.  The "Confirm Deletion" button component is used as the default if no `confirmDeletionRenderer` is passed in.
This is not a breaking API change and all things remain fully backwards compatible.
> Expose a confirmDeletionRenderer prop for FileBrowser

- src/base-file.js
- src/base-folder.js
This PR adds the ability for the user to use either the ctrl or meta (cmd on mac) keys to select multiple rows. Please see #93 for more details.
Please let me know if there are tests/examples that should be updated as well in this PR. 
Thanks!
Resolves #93
> OSX compatible multiple selection

- src/base-file.js
This fixes the issue for me. 
I also spent some time trying to get the drag preview to represent all selected files when dragging more than one file, however, that looked like it would be more trouble than it was worth based on how `react-dnd`/HTML5 drag and drop work. 
If you have any issue/concerns with this fix, let me know and I'll be happy to address them.
> Issue 92 bug fix

- package.json
- src/base-folder.js
- yarn.lock
* Fully fixes #107 and partially fixes #27
* react dnd bumped to version 8.x, as version 9+ has deprecated decorators and HOCs and will cause us to refactor parts of the app(which we should anyway)
> Bump react-dnd version and fix folder creation when rename is disabled

- src/browser.js
Fixes #108
* Place more aggressive checks to clear selection if new folder or file was being created and user aborts by clicking outside or any other way
* There was another issue on empty structure(no files or folder yet) if i tried to create a new folder, it was impossible, on the input field click it just focused out, this might had been some edge case happening for me only but i fixed it as well
PS: Its not the best fix possible, I patched this in a hurry for our internal use, but thought should contribute back in whatever state it is. Seems to work fine for us for now. I will keep posted if we discover any other issue.
> Fix new folder and file creation spamming issues

- package.json
- src/browser.js
- src/files/list-thumbnail.js
- src/files/table.js
- src/groupers/by-modified.js
- src/groupers/utils.js
- src/sorters/by-modified.js
- stories/index.js
- yarn.lock
> Replace moment with date-fns

- src/icons/FontAwesome.js
fixes #131 
* Rename icon fontawesome 5 prefix from `far` to `fas` as regular i-cursor is not available in the free version of fontawesome
Reference [regular](https://fontawesome.com/icons/i-cursor?style=regular), [solid](https://fontawesome.com/icons/i-cursor?style=solid)
> issue/131 Corrected fontawesome 5 rename icon

- src/actions/default.js
- src/browser.js
resolve #133 
* `getFiles` function to encapsulate the `files` part of the `render` function
* `getSelectedItems` function to encapsulate the `selectedItems` part of the `render` function
* `canDownloadFolder` and `onDownloadFolder`  functions and their configs
* `handleActionBarDownloadClick` function to check if the selection is a folder using new `getFiles` and `getSelectedItems` functions
* `render` function uses the new `getFiles` and `getSelectedItems` functions
* Switched to using `utils.isFolder` rather than a `size === 0` comparison for folders
> issue/133 Added onDownloadFolder

- src/browser.js
Fixes: https://github.com/uptick/react-keyed-file-browser/issues/115
If your files look like
`/a/b/c.txt, /a/b/d.txt`, then you will get undefined for the folder calls because no folders have been defined.
If you have `/a/, a/b/, /a/b/c.txt, /a/b/d.txt` then you will get the folder you are looking for.
The problem lies in https://github.com/uptick/react-keyed-file-browser/blob/master/src/browser.js#L178
where .find is looking for an exact match in all the files.
I would argue that a user should not have to specify all the folders and if a prefix exists. The onSelect callback should return a folder with 0 for modified and size.
> onSelectFolder returns folder from file path instead of undefined

- .storybook/preview.js
- README.md
- index.js
- package.json
- src/browser.js
- src/files/list-thumbnail.js
- src/files/table.js
- src/folders/list-thumbnail.js
- src/folders/table.js
- src/headers/table.js
- src/icons/index.js
- stories/index.js
- yarn.lock
Before we transition into using esbuild as our default bundler. I wanted to clean up the dependencies to rid of un-needed transformations.
During this process, I noticed how outdated some of our dependencies are. I have updated them.
This includes changing the now deprecated `Drag and Drop Context Dectorator` provided by [react-dnd](https://react-dnd.github.io/react-dnd/docs/api/dnd-provider) with the `DNDProvider Component` instead.
> refactor: updated dependencies and replaced the DragDropContext decorator.

- src/base-folder.js
If there's a `submit` event listener higher up (i.e. on document), renaming and deleting will allow that listener to fire. This shouldn't happen as the rename and delete processes should be entirely contained (hence why we have `preventDefault` in there.) This fixes that.
> fix: stop rename and delete submit events from propagating

- src/browser.js
* added the second argument to _onFolderOpen_ and _onFolderClose_ (the need was to manipulate the browser's state from these callbacks)
> fix: adds browser props to onFolder* callbacks

- package.json
- src/browser.js
The message for "no files" scenario can be only a text. I've extended proptypes to allow using a component.
The message for "no files matching the name filter" scenario is hardcoded. I've added a new prop to allow customizing that message.
Tested manually in our codebase.
> feat: noFilesMessage can be a component + added noMatchingFilesMessage

- src/files/list-thumbnail.js
- src/files/table.js
- src/folders/list-thumbnail.js
- src/folders/table.js
Hi,
can you please review patch to correctly import the `lodash.flow` package. It fixes #252.
The package was incorrectly imported using `lodash/flow`, which expected the full `lodash` package to be present for the `/` syntax to work.
The way it got away with it so far is because `lodash` is installed locally as part of storybook in development.
Thanks
> correct lodash.flow imports
